language: bash
services:
  - docker
env:
  - STACK=cedar-14 GOOGLE_CHROME_CHANNEL=stable
  - STACK=cedar-14 GOOGLE_CHROME_CHANNEL=beta
  - STACK=cedar-14 GOOGLE_CHROME_CHANNEL=unstable

  - STACK=heroku-16 GOOGLE_CHROME_CHANNEL=stable
  - STACK=heroku-16 GOOGLE_CHROME_CHANNEL=beta
  - STACK=heroku-16 GOOGLE_CHROME_CHANNEL=unstable

  - STACK=heroku-18 GOOGLE_CHROME_CHANNEL=stable
  - STACK=heroku-18 GOOGLE_CHROME_CHANNEL=beta
  - STACK=heroku-18 GOOGLE_CHROME_CHANNEL=unstable

  - STACK=heroku-20 GOOGLE_CHROME_CHANNEL=stable
  - STACK=heroku-20 GOOGLE_CHROME_CHANNEL=beta
  - STACK=heroku-20 GOOGLE_CHROME_CHANNEL=unstable

  # Test relying on the buildpack's default Chrome channel.
  - STACK=heroku-18
script:
  - ./support/test.sh "${STACK}"
jobs:
  allow_failures:
    # Cedar-14 currently fails with:
    # "error while loading shared libraries: libgbm.so.1".
    - env: STACK=cedar-14 GOOGLE_CHROME_CHANNEL=stable
    - env: STACK=cedar-14 GOOGLE_CHROME_CHANNEL=beta
    - env: STACK=cedar-14 GOOGLE_CHROME_CHANNEL=unstable
